import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const STATES_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "states");
const OUT = path.join(ROOT, "src/lib/india-map.ts");

// Keep in sync with geo.ts BOUNDS + MAP_VIEWBOX.
const BOUNDS = { minLat: 6.5, maxLat: 37.2, minLng: 68.1, maxLng: 97.4 };
const VB = { width: 560, height: 588 };

const round = (n) => Math.round(n * 10) / 10;
function project([lng, lat]) {
  const x = ((lng - BOUNDS.minLng) / (BOUNDS.maxLng - BOUNDS.minLng)) * VB.width;
  const y = ((BOUNDS.maxLat - lat) / (BOUNDS.maxLat - BOUNDS.minLat)) * VB.height;
  return [x, y];
}

// Douglas–Peucker; preserves shape, drops redundant colinear points.
function rdp(pts, eps) {
  if (pts.length < 3) return pts;
  let dmax = 0,
    idx = 0;
  const [ax, ay] = pts[0],
    [bx, by] = pts[pts.length - 1];
  const dx = bx - ax,
    dy = by - ay;
  const len = Math.hypot(dx, dy) || 1;
  for (let i = 1; i < pts.length - 1; i++) {
    const [px, py] = pts[i];
    const d = Math.abs((px - ax) * dy - (py - ay) * dx) / len;
    if (d > dmax) {
      dmax = d;
      idx = i;
    }
  }
  if (dmax > eps) {
    return rdp(pts.slice(0, idx + 1), eps)
      .slice(0, -1)
      .concat(rdp(pts.slice(idx), eps));
  }
  return [pts[0], pts[pts.length - 1]];
}

// RDP assumes an open polyline with distinct endpoints. A closed ring's start
// == end, which degenerates the base segment and collapses everything. Split
// the ring at its farthest-from-start vertex into two open halves, simplify
// each, then rejoin.
function simplifyRing(pts, eps) {
  if (pts.length < 4) return pts;
  const [x0, y0] = pts[0];
  let far = 1,
    fd = -1;
  for (let i = 1; i < pts.length; i++) {
    const d = (pts[i][0] - x0) ** 2 + (pts[i][1] - y0) ** 2;
    if (d > fd) {
      fd = d;
      far = i;
    }
  }
  const a = rdp(pts.slice(0, far + 1), eps);
  const b = rdp(pts.slice(far), eps);
  return a.slice(0, -1).concat(b);
}

function ringPath(ring, eps) {
  let pts = ring.map(project);
  // shoelace area to drop specks (tiny islands, border slivers)
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const [x1, y1] = pts[i],
      [x2, y2] = pts[(i + 1) % pts.length];
    a += x1 * y2 - x2 * y1;
  }
  if (Math.abs(a / 2) < 4) return null; // < 4 sq px → skip
  pts = simplifyRing(pts, eps);
  if (pts.length < 3) return null;
  return "M" + pts.map(([x, y]) => `${round(x)} ${round(y)}`).join("L") + "Z";
}

const EPS = 1.1;
if (!fs.existsSync(STATES_DIR)) {
  console.error(
    `Missing ${STATES_DIR}\nPlace per-state India GeoJSON files there, then re-run.`,
  );
  process.exit(1);
}

const STATE_FILES = fs.readdirSync(STATES_DIR).filter((f) => f.endsWith(".geojson"));

// Each state file is district-level; we render every district ring. The fills
// tile into the country silhouette and the thin strokes read as internal
// borders (kept subtle in the component so the map doesn't look busy).
const statePaths = []; // { name, d }
for (const file of STATE_FILES) {
  const g = JSON.parse(fs.readFileSync(path.join(STATES_DIR, file), "utf8"));
  let d = "";
  for (const f of g.features) {
    const geom = f.geometry;
    const polys = geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
    for (const poly of polys) {
      const p = ringPath(poly[0], EPS);
      if (p) d += p;
    }
  }
  if (d) statePaths.push({ name: file.replace(".geojson", ""), d });
}

const combined = statePaths.map((s) => s.d).join("");
const arr = statePaths
  .map((s) => `  { name: ${JSON.stringify(s.name)}, d: ${JSON.stringify(s.d)} }`)
  .join(",\n");

fs.writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/map/gen_map.mjs from public-domain per-state India GeoJSON
// (udit-001/india-maps-data, MIT). Projected to match geo.ts BOUNDS + VIEWBOX.
// STATE_PATHS render as filled shapes with thin strokes → silhouette + borders.
export const STATE_PATHS: { name: string; d: string }[] = [
${arr}
];

// One compound path of all states, for a single filled silhouette layer.
export const INDIA_SILHOUETTE =
  ${JSON.stringify(combined)};
`,
);

console.log("wrote", OUT);
console.log("states:", statePaths.length, "| total path chars:", combined.length);
